## O que são Attention Mechanisms?

## Por que são importantes?

## Como os Attention Mechanisms funcionam?

## Implementando um Mecanismo de Atenção Simples

Importando a Biblioteca  
Objetivo: Importar a biblioteca NumPy, que é usada para realizar operações matemáticas e manipulação de arrays de maneira eficiente.


In [1]:
import numpy as np


## Definindo a Função de Atenção Simples
Objetivo: Criar uma função que aplica pesos de atenção às entradas e gera uma saída ponderada.

inputs: Um array de entradas, onde cada linha representa uma sequência de dados.

attention_weights: Um array de pesos de atenção, onde cada valor representa a importância da respectiva linha de entrada.

Criar um array de entradas onde cada linha representa uma sequência de dados.

Formato: Um array 3x4 (3 linhas e 4 colunas).

In [2]:
def attention_mechanism(inputs, attention_weights):
    # Multiplicar os pesos de atenção com as entradas
    weighted_inputs = inputs * attention_weights[:, np.newaxis]
    return np.sum(weighted_inputs, axis=0)


In [3]:
inputs = np.array([
    [1, 0, 1, 0],
    [0, 2, 0, 2],
    [1, 1, 1, 1]
    ])


In [4]:
attention_weights = np.array([0.1, 0.2, 0.7])

# Aplicando o mecanismo de atenção
output = attention_mechanism(inputs, attention_weights)

print("Inputs:")
print(inputs)
print("Attention Weights:")
print(attention_weights)
print("Output com Atenção Aplicada:")
print(output)

Inputs:
[[1 0 1 0]
 [0 2 0 2]
 [1 1 1 1]]
Attention Weights:
[0.1 0.2 0.7]
Output com Atenção Aplicada:
[0.8 1.1 0.8 1.1]


## Visão geral do notebook
Este caderno demonstra, passo a passo, como funciona um mecanismo de atenção simplificado: importamos o NumPy, definimos uma função `attention_mechanism` que calcula a combinação ponderada dos vetores de entrada e, em seguida, criamos entradas e pesos para observar o efeito da atenção sobre cada componente. Também exibimos os valores intermediários (entradas, pesos e saída) para reforçar a intuição matemática.

### O que você aprende aqui
1. **Estrutura básica de atenção** — entender como multiplicar pesos de atenção pela sequência de vetores e realizar a soma ponderada.
2. **Implementação em NumPy** — criar funções vetorizadas simples, reutilizáveis para outros experimentos.
3. **Interpretação dos resultados** — analisar como diferentes pesos enfatizam partes específicas da entrada, preparando o terreno para versões mais avançadas de self-attention e cross-attention discutidas nas outras aulas.

Use este notebook como referência rápida antes de mergulhar nos exemplos seguintes (`Self_attention.ipynb` e `Cross_Attention.ipynb`), pois ele consolida a intuição necessária para compreender arquiteturas modernas baseadas em atenção.