<a href="https://colab.research.google.com/github/ThamirisAdriano/gen_ia_mlet/blob/main/Attention_Mechanisms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###O que são Attention Mechanisms?

###Por que são importantes?

###Como os Attention Mechanisms funcionam?

##Implementando um Mecanismo de Atenção Simples

Importantdo a Biblioteca
Objetivo: Importar a biblioteca NumPy, que é usada para realizar operações matemáticas e manipulação de arrays de maneira eficiente.


In [ ]:
import numpy as np


##Definindo a Função de Atenção Simples
Objetivo: Criar uma função que aplica pesos de atenção às entradas e gera uma saída ponderada.

inputs: Um array de entradas, onde cada linha representa uma sequência de dados.

attention_weights: Um array de pesos de atenção, onde cada valor representa a importância da respectiva linha de entrada.

Criar um array de entradas onde cada linha representa uma sequência de dados.

Formato: Um array 3x4 (3 linhas e 4 colunas).

In [ ]:
def attention_mechanism(inputs, attention_weights):
    # Multiplicar os pesos de atenção com as entradas
    weighted_inputs = inputs * attention_weights[:, np.newaxis]
    return np.sum(weighted_inputs, axis=0)

    inputs = np.array([
    [1, 0, 1, 0],
    [0, 2, 0, 2],
    [1, 1, 1, 1]
])


In [ ]:
attention_weights = np.array([0.1, 0.2, 0.7])

# Aplicando o mecanismo de atenção
output = attention_mechanism(inputs, attention_weights)

print("Inputs:")
print(inputs)
print("Attention Weights:")
print(attention_weights)
print("Output com Atenção Aplicada:")
print(output)

Inputs:
[[1 0 1 0]
 [0 2 0 2]
 [1 1 1 1]]
Attention Weights:
[0.1 0.2 0.7]
Output com Atenção Aplicada:
[0.8 1.1 0.8 1.1]
